version: '3'

services: 

  app:
    build: 
      context: ./
    container_name: tarefas_app
    command: npm run test
    # command: node index.js
    # volumes: 
    #   - ./:/usr/src/app
    #   - /usr/src/app/node_modules
